commits:
    type: Web
    title: Conventional Commits
    url: https://www.conventionalcommits.org/en/v1.0.0/

jee:
    type: Web
    title: Développer avec Java EE
    url: https://youtu.be/jevdND1NBVs?si=Qq4JyL0pw7eBoP7A

cahier_des_charges:
    type: Web
    title: 'Créer un cahier des charges : Le guide complet'
    url: https://www.nubios.be/cahier-des-charges-application-mobile-guide-complet